// Builds every brand output from brand/tokens.json + brand/profile.json.
//   brand/dist/tokens.resolved.json  → references resolved (read by Tailwind, OG/social routes, Python)
//   app/brand.css                    → CSS custom properties for the website
//   brand/dist/*.html                → email templates with hex values inlined
// Run: npm run brand   (also runs automatically before dev/build)
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const tokens = JSON.parse(read("brand/tokens.json"));
const profile = JSON.parse(read("brand/profile.json"));

// "{name}" references resolve against semantic colors, then primitives, then "gradient.x".
function lookup(name) {
  if (name.startsWith("gradient.")) return tokens.semantic.gradient[name.slice(9)];
  return tokens.semantic.color[name] ?? tokens.primitive.color[name];
}

function resolveString(value, depth = 0) {
  if (depth > 10) throw new Error(`Circular token reference: ${value}`);
  return value.replace(/\{([\w.-]+)\}/g, (match, name) => {
    const hit = lookup(name);
    if (hit === undefined) throw new Error(`Unknown token reference ${match}`);
    return resolveString(hit, depth + 1);
  });
}

function resolve(node) {
  if (typeof node === "string") return resolveString(node);
  if (Array.isArray(node)) return node.map(resolve);
  if (node && typeof node === "object") {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, resolve(v)]));
  }
  return node;
}

const resolved = resolve(tokens);

// Flat CSS variable map shared by app/brand.css and the resolved JSON.
const cssVars = {};
for (const [k, v] of Object.entries(resolved.semantic.color)) cssVars[`--color-${k}`] = v;
for (const [k, v] of Object.entries(resolved.semantic.gradient)) cssVars[`--gradient-${k}`] = v;
for (const [k, v] of Object.entries(resolved.radius)) cssVars[`--radius-${k}`] = v;
for (const [k, v] of Object.entries(resolved.spacing)) cssVars[`--space-${k}`] = v;
resolved.cssVars = cssVars;

mkdirSync(join(root, "brand/dist"), { recursive: true });
writeFileSync(
  join(root, "brand/dist/tokens.resolved.json"),
  JSON.stringify(resolved, null, 2) + "\n",
);

const banner = "/* AUTO-GENERATED by scripts/build-brand.mjs from brand/tokens.json — do not edit. */\n";
const css =
  banner +
  ":root {\n" +
  Object.entries(cssVars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n") +
  "\n}\n";
writeFileSync(join(root, "app/brand.css"), css);

// Email templates: [[t.path.to.token]] and [[p.path]] are filled at build time.
// {{jinja_placeholders}} are left untouched for the Python sender.
function get(obj, path) {
  return path.split(".").reduce((o, k) => (o == null ? undefined : o[k]), obj);
}
function fill(template, file) {
  return template.replace(/\[\[(t|p)\.([\w.-]+)\]\]/g, (match, scope, path) => {
    const value = get(scope === "t" ? resolved : profile, path);
    if (value === undefined) throw new Error(`${file}: unknown placeholder ${match}`);
    return Array.isArray(value) ? value.join(" · ") : String(value);
  });
}

const templateDir = join(root, "brand/templates");
const built = [];
for (const file of readdirSync(templateDir).filter((f) => f.endsWith(".html"))) {
  writeFileSync(join(root, "brand/dist", file), fill(readFileSync(join(templateDir, file), "utf8"), file));
  built.push(file);
}

console.log(`brand: ${Object.keys(cssVars).length} CSS vars, templates: ${built.join(", ") || "none"}`);
